// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Unigis.PuntoVentas.BackEnd.Data;

#nullable disable

namespace Unigis.PuntoVentas.BackEnd.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250516165740_Migracion inicial")]
    partial class Migracioninicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Unigis.PuntoVentas.BackEnd.Data.Entidades.PuntoDeVentas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("IdZona")
                        .HasColumnType("int");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(10, 7)");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(10, 7)");

                    b.Property<decimal>("Ventas")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdZona");

                    b.ToTable("PuntoVentas");
                });

            modelBuilder.Entity("Unigis.PuntoVentas.BackEnd.Data.Entidades.Zonas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Zonas");
                });

            modelBuilder.Entity("Unigis.PuntoVentas.BackEnd.Data.Entidades.PuntoDeVentas", b =>
                {
                    b.HasOne("Unigis.PuntoVentas.BackEnd.Data.Entidades.Zonas", "Zona")
                        .WithMany()
                        .HasForeignKey("IdZona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zona");
                });
#pragma warning restore 612, 618
        }
    }
}
